const BASE = '../app-assets/3D';

export const BODIES = [
  {
    id: 'sol', name: 'Sol',
    categoria: 'Estrella', clasificacion: 'Enana Amarilla (Tipo G2V)',
    color: '#FDB813', archivo: `${BASE}/Sol.glb`, cameraOrbit: '0deg 80deg 200%',
    funcion: 'Centro gravitacional y fuente de energía del sistema solar',
    ubicacion: 'Centro del sistema solar',
    relacion: 'Todos los planetas, lunas, asteroides y cometas',
    tamano: 'Diámetro 1.392.700 km — 109× la Tierra',
    importancia: 'Fuente del 99,99% de la energía del sistema; su gravedad mantiene en órbita a todos los cuerpos celestes conocidos',
    descripcion: 'El Sol es la estrella en el centro del Sistema Solar. Es una esfera de plasma caliente que genera energía mediante fusión nuclear en su núcleo. Contiene el 99,86% de toda la masa del sistema.',
    datoCurioso: 'La luz del Sol tarda 8 minutos y 20 segundos en llegar a la Tierra.',
    datos: { 'Diámetro': '1.392.700 km', 'Masa': '1,989 × 10³⁰ kg', 'Temp. Superficie': '5.500 °C', 'Temp. Corona': '~2.000.000 °C', 'Rotación': '25–35 días', 'Edad': '4.600 Ma', 'Lunas': 'N/A', 'Composición': 'H₂ 73%, He 25%' },
    curiosidades: ['Más de 1.300.000 Tierras cabrían dentro del Sol', 'Su temperatura central alcanza los 15 millones de °C', 'La luz tarda 8 min 20 s en llegar a la Tierra', 'Ha consumido ~la mitad de su hidrógeno en 4.600 Ma'],
    nota: 'En ~5.000 Ma el Sol se expandirá como gigante roja, devorará a Mercurio y Venus, y luego colapsará en una enana blanca.'
  },
  {
    id: 'mercurio', name: 'Mercurio',
    categoria: 'Planeta Rocoso', clasificacion: 'Planeta Terrestre',
    color: '#9E9080', archivo: `${BASE}/Mercurio.glb`, cameraOrbit: '0deg 80deg 180%',
    funcion: 'Planeta rocoso con los mayores extremos térmicos del sistema solar',
    ubicacion: '1.ª órbita solar — 0,39 UA del Sol',
    relacion: 'Sol (cuerpo más próximo), Venus (segundo planeta)',
    tamano: 'Diámetro 4.879 km — 38% del diámetro terrestre',
    importancia: 'Clave para entender la formación planetaria; su núcleo sobredimensionado desafía los modelos estándar de acreción',
    descripcion: 'Mercurio es el planeta más pequeño y más cercano al Sol. Su superficie sin atmósfera protectora está cubierta de cráteres de impacto y experimenta los mayores rangos de temperatura del sistema solar.',
    datoCurioso: 'A pesar de ser el planeta más cercano al Sol, no es el más caliente del sistema solar.',
    datos: { 'Diámetro': '4.879 km', 'Masa': '3,30 × 10²³ kg', 'Temp. Máx.': '430 °C', 'Temp. Mín.': '−180 °C', 'Rotación': '58,6 días', 'Órbita': '88 días', 'Lunas': '0', 'Dist. al Sol': '0,39 UA' },
    curiosidades: ['Un año en Mercurio dura solo 88 días terrestres', 'A pesar de ser el más cercano al Sol, no es el más caliente', 'Su núcleo de hierro ocupa el 85% de su radio total', 'Sus "escarpes de lobulillos" indican que el planeta se encoge'],
    nota: 'La sonda MESSENGER (NASA) orbitó Mercurio 2011–2015, cartografiando el 100% de su superficie por primera vez en la historia.'
  },
  {
    id: 'venus', name: 'Venus',
    categoria: 'Planeta Rocoso', clasificacion: 'Planeta Terrestre',
    color: '#E8C87A', archivo: `${BASE}/Venus.glb`, cameraOrbit: '0deg 80deg 180%',
    funcion: 'Segundo planeta; el más caliente por su efecto invernadero extremo',
    ubicacion: '2.ª órbita solar — 0,72 UA del Sol',
    relacion: 'Tierra (planeta vecino interior), Sol',
    tamano: 'Diámetro 12.104 km — 95% del diámetro terrestre',
    importancia: 'Caso de estudio extremo del efecto invernadero; gemelo planetario deformado que advierte sobre el cambio climático',
    descripcion: 'Venus es el segundo planeta y el más parecido a la Tierra en tamaño, pero con condiciones extremas. Su densa atmósfera de CO₂ genera el efecto invernadero más intenso del sistema solar.',
    datoCurioso: 'Un día en Venus es más largo que su propio año orbital.',
    datos: { 'Diámetro': '12.104 km', 'Masa': '4,87 × 10²⁴ kg', 'Temperatura': '465 °C (promedio)', 'Atmósfera': 'CO₂ 96,5%, N₂ 3,5%', 'Rotación': '243 días (retrógrado)', 'Órbita': '225 días', 'Lunas': '0', 'Dist. al Sol': '0,72 UA' },
    curiosidades: ['Es el planeta más caliente del sistema solar (465 °C)', 'Rota al revés — el Sol sale por el oeste', 'Un día venusino es más largo que su propio año', 'Su presión atmosférica es 92 × la terrestre'],
    nota: 'Las sondas soviéticas Venera (1970–1985) fueron las únicas en aterrizar en Venus, sobreviviendo entre 23 minutos y 2 horas.'
  },
  {
    id: 'tierra', name: 'Tierra',
    categoria: 'Planeta Rocoso', clasificacion: 'Planeta Terrestre',
    color: '#3B78C3', archivo: `${BASE}/Tierra.glb`, cameraOrbit: '0deg 80deg 180%',
    funcion: 'Único planeta conocido con vida; hogar de toda la humanidad',
    ubicacion: '3.ª órbita solar — 1 UA (149,6 millones de km)',
    relacion: 'Luna (satélite natural), Sol, Marte (vecino exterior)',
    tamano: 'Diámetro 12.742 km; radio ecuatorial 6.378 km',
    importancia: 'Único planeta conocido con vida; alberga toda la biodiversidad documentada del cosmos',
    descripcion: 'La Tierra es el tercer planeta y el único conocido que alberga vida. Su atmósfera de nitrógeno y oxígeno, su campo magnético y el agua líquida en su superficie crean condiciones únicas.',
    datoCurioso: 'El 71% de la superficie terrestre está cubierta por agua líquida.',
    datos: { 'Diámetro': '12.742 km', 'Masa': '5,97 × 10²⁴ kg', 'Temperatura': '15 °C (promedio)', 'Atmósfera': 'N₂ 78%, O₂ 21%, Ar 1%', 'Rotación': '23 h 56 min', 'Órbita': '365,25 días', 'Lunas': '1 (Luna)', 'Dist. al Sol': '1 UA (149,6 M km)' },
    curiosidades: ['Es el planeta de mayor densidad del sistema solar', 'El 71% de su superficie está cubierta de agua', 'Su campo magnético nos protege del viento solar', 'Único planeta con tectónica de placas activa confirmada'],
    nota: 'La Tierra es el único cuerpo celeste donde se sabe con certeza que existe vida, aunque estadísticamente parece improbable que sea el único lugar en el universo.'
  },
  {
    id: 'luna', name: 'Luna',
    categoria: 'Satélite Natural', clasificacion: 'Satélite Natural',
    color: '#B8B0A5', archivo: `${BASE}/Luna.glb`, cameraOrbit: '0deg 80deg 180%',
    funcion: 'Estabiliza el eje de la Tierra y genera las mareas oceánicas',
    ubicacion: 'Órbita terrestre — 384.400 km de la Tierra',
    relacion: 'Tierra (planeta huésped), Sol',
    tamano: 'Diámetro 3.474 km — 27% del diámetro terrestre',
    importancia: 'Estabiliza el eje axial terrestre; primer y único destino tripulado extraterrestre de la humanidad',
    descripcion: 'La Luna es el único satélite natural de la Tierra y el quinto satélite más grande del sistema solar. Es el único cuerpo extraterrestre donde los seres humanos han pisado, durante las misiones Apollo (1969–1972).',
    datoCurioso: 'La Luna se aleja de la Tierra 3,8 cm cada año.',
    datos: { 'Diámetro': '3.474 km', 'Masa': '7,35 × 10²² kg', 'Temperatura': '−173 °C a 127 °C', 'Atmósfera': 'Exosfera tenue', 'Rotación': '27,3 días (sincrónica)', 'Órbita (Tierra)': '27,3 días', 'Dist. a Tierra': '384.400 km (media)' },
    curiosidades: ['Siempre muestra la misma cara hacia la Tierra', 'Se aleja 3,8 cm de la Tierra cada año', 'Genera las mareas en los océanos terrestres', 'Solo 12 personas han caminado sobre ella (1969–1972)'],
    nota: 'Probablemente se formó hace 4.500 Ma cuando un objeto del tamaño de Marte (Theia) colisionó con la Tierra primitiva, eyectando material que se acumuló en órbita.'
  },
  {
    id: 'marte', name: 'Marte',
    categoria: 'Planeta Rocoso', clasificacion: 'Planeta Terrestre',
    color: '#C1440E', archivo: `${BASE}/Marte.glb`, cameraOrbit: '0deg 80deg 180%',
    funcion: 'Planeta rojo; principal candidato a colonización humana futura',
    ubicacion: '4.ª órbita solar — 1,52 UA del Sol',
    relacion: 'Tierra (vecino interior), Júpiter (vecino exterior), Fobos y Deimos',
    tamano: 'Diámetro 6.779 km — 53% del diámetro terrestre',
    importancia: 'Principal candidato a colonización humana; evidencia sólida de océanos líquidos en el pasado reciente',
    descripcion: 'Marte, el Planeta Rojo, debe su color al óxido de hierro en su superficie. Alberga el volcán más grande del sistema solar (Monte Olimpo, 21,9 km) y el cañón más extenso (Valles Marineris, 4.000 km).',
    datoCurioso: 'Monte Olimpo en Marte es el volcán más alto del sistema solar con 21,9 km de altura.',
    datos: { 'Diámetro': '6.779 km', 'Masa': '6,39 × 10²³ kg', 'Temperatura': '−65 °C (promedio)', 'Atmósfera': 'CO₂ 95,3%, N₂ 2,6%', 'Rotación': '24 h 37 min', 'Órbita': '687 días', 'Lunas': '2 (Fobos y Deimos)', 'Dist. al Sol': '1,52 UA' },
    curiosidades: ['Monte Olimpo: el volcán más alto del sistema solar', 'Tiene dos lunas irregulares capturadas del cinturón de asteroides', 'Un día marciano dura 24 h 37 min — casi igual que en la Tierra', 'Evidencias confirman océanos líquidos hace 3.500 millones de años'],
    nota: 'El rover Perseverance recolecta muestras en el cráter Jezero para una futura misión de retorno que las traería a la Tierra circa 2033.'
  },
  {
    id: 'jupiter', name: 'Júpiter',
    categoria: 'Gigante Gaseoso', clasificacion: 'Gigante Gaseoso (Joviano)',
    color: '#C88B3A', archivo: `${BASE}/Jupiter.glb`, cameraOrbit: '0deg 80deg 180%',
    funcion: 'Escudo gravitacional del sistema solar; desvía asteroides y cometas',
    ubicacion: '5.ª órbita solar — 5,20 UA del Sol',
    relacion: 'Saturno (vecino exterior), 95 lunas incluyendo Europa y Ganímedes',
    tamano: 'Diámetro 139.820 km — 11× la Tierra; masa 318× la Tierra',
    importancia: 'Escudo gravitacional del sistema interior; su luna Europa es candidata #1 a vida extraterrestre',
    descripcion: 'Júpiter es el planeta más grande — 1.321 Tierras cabrían en su interior. La Gran Mancha Roja es una tormenta anticiclónica activa desde hace más de 350 años.',
    datoCurioso: 'La luna Europa de Júpiter tiene un océano subsuperficial mayor que todos los océanos terrestres juntos.',
    datos: { 'Diámetro': '139.820 km', 'Masa': '1,90 × 10²⁷ kg', 'Temperatura': '−108 °C (nubes)', 'Composición': 'H₂ 90%, He 10%', 'Rotación': '9 h 55 min', 'Órbita': '11,86 años', 'Lunas': '95 conocidas', 'Dist. al Sol': '5,20 UA' },
    curiosidades: ['Su gravedad desvía asteroides y cometas que vendrían hacia la Tierra', 'La Gran Mancha Roja mide ~16.000 km de ancho', 'Europa tiene un océano subsuperficial mayor que todos los de la Tierra', 'Su día es el más corto del sistema solar: 9 h 55 min'],
    nota: 'Europa (luna de Júpiter) es el candidato #1 a vida extraterrestre: tiene un océano de agua salada bajo su corteza de hielo, calentado por fuerzas de marea.'
  },
  {
    id: 'saturno', name: 'Saturno',
    categoria: 'Gigante Gaseoso', clasificacion: 'Gigante Gaseoso (Joviano)',
    color: '#E8D5A0', archivo: `${BASE}/Saturno.glb`, cameraOrbit: '0deg 75deg 200%',
    funcion: 'Gigante gaseoso con el sistema de anillos más espectacular del sistema solar',
    ubicacion: '6.ª órbita solar — 9,58 UA del Sol',
    relacion: 'Júpiter (vecino interior), Urano (vecino exterior), 146 lunas incluyendo Titán',
    tamano: 'Diámetro 116.460 km (9,5× la Tierra); con anillos alcanza 282.000 km',
    importancia: 'Sistema de anillos de referencia en astronomía; Titán posee química orgánica compleja y posible vida prebiótica',
    descripcion: 'Saturno es el sexto planeta, universalmente reconocible por su espectacular sistema de anillos. Es el planeta menos denso del sistema solar — flotaría en el agua.',
    datoCurioso: 'Saturno es el único planeta del sistema solar menos denso que el agua.',
    datos: { 'Diámetro': '116.460 km', 'Masa': '5,68 × 10²⁶ kg', 'Temperatura': '−138 °C (nubes)', 'Composición': 'H₂ 96%, He 3%', 'Rotación': '10 h 34 min', 'Órbita': '29,45 años', 'Lunas': '146 conocidas', 'Dist. al Sol': '9,58 UA' },
    curiosidades: ['Es el único planeta del sistema solar menos denso que el agua', 'Sus anillos se extienden 282.000 km con solo ~20 m de grosor', 'Titán tiene atmósfera densa con ríos y lagos de metano líquido', 'Sus vientos en la atmósfera alcanzan 1.800 km/h'],
    nota: 'Los anillos de Saturno son geológicamente jóvenes (100–400 Ma) y desaparecerán dentro de ~100 Ma al caer en espiral por interacciones gravitacionales.'
  },
  {
    id: 'urano', name: 'Urano',
    categoria: 'Gigante de Hielo', clasificacion: 'Gigante de Hielo',
    color: '#7DE8E8', archivo: `${BASE}/Urano.glb`, cameraOrbit: '0deg 80deg 180%',
    funcion: 'Gigante de hielo que gira de lado con inclinación axial de 97,77°',
    ubicacion: '7.ª órbita solar — 19,19 UA del Sol',
    relacion: 'Saturno (vecino interior), Neptuno (vecino exterior), 27 lunas',
    tamano: 'Diámetro 50.724 km — 4× el diámetro terrestre',
    importancia: 'Primer planeta descubierto telescópicamente; modelo clave de gigantes de hielo con eje axial extremo',
    descripcion: 'Urano es el séptimo planeta y el primero descubierto con telescopio (1781, William Herschel). Gira de lado con su eje inclinado 97,77°, probablemente por una colisión antigua.',
    datoCurioso: 'Urano tiene la temperatura atmosférica más baja del sistema solar: −224 °C.',
    datos: { 'Diámetro': '50.724 km', 'Masa': '8,68 × 10²⁵ kg', 'Temperatura': '−195 °C (nubes)', 'Composición': 'H₂, He, CH₄ (metano)', 'Rotación': '17 h 14 min', 'Órbita': '84 años', 'Lunas': '27 conocidas', 'Dist. al Sol': '19,19 UA' },
    curiosidades: ['Tiene la temperatura atmosférica más baja: −224 °C', 'Gira casi acostado — su eje es paralelo a su órbita', 'Tiene 13 anillos y 27 lunas con nombres de Shakespeare', 'Solo Voyager 2 lo ha visitado, en un sobrevuelo de 1986'],
    nota: 'La misión Uranus Orbiter and Probe, prioridad #1 de la NASA para la próxima década, está planificada para lanzar en 2031 y llegar circa 2044.'
  },
  {
    id: 'neptuno', name: 'Neptuno',
    categoria: 'Gigante de Hielo', clasificacion: 'Gigante de Hielo',
    color: '#3F54BA', archivo: `${BASE}/Neptuno.glb`, cameraOrbit: '0deg 80deg 180%',
    funcion: 'Planeta más exterior; vientos más veloces del sistema solar',
    ubicacion: '8.ª órbita solar — 30,07 UA del Sol',
    relacion: 'Urano (vecino interior), Cinturón de Kuiper, 16 lunas incluyendo Tritón',
    tamano: 'Diámetro 49.244 km — 3,9× el diámetro terrestre',
    importancia: 'Predicho matemáticamente antes de ser observado; sus vientos supersónicos aún no tienen explicación completa',
    descripcion: 'Neptuno es el octavo y último planeta. Fue predicho matemáticamente antes de ser observado. Sus vientos supersónicos de 2.100 km/h son los más rápidos del sistema solar.',
    datoCurioso: 'Neptuno fue descubierto en 1846 por predicción matemática, antes de ser observado directamente.',
    datos: { 'Diámetro': '49.244 km', 'Masa': '1,02 × 10²⁶ kg', 'Temperatura': '−200 °C (nubes)', 'Composición': 'H₂, He, CH₄ (metano)', 'Rotación': '16 h 6 min', 'Órbita': '164,8 años', 'Lunas': '16 conocidas', 'Dist. al Sol': '30,07 UA' },
    curiosidades: ['Descubierto en 1846 por predicción matemática, antes de observarlo', 'Vientos de 2.100 km/h — los más rápidos del sistema solar', 'La Gran Mancha Oscura era una tormenta del tamaño de la Tierra', 'Tritón orbita al revés — fue capturado del Cinturón de Kuiper'],
    nota: 'Tritón, su luna mayor, está en órbita decadente. En ~3.600 Ma las fuerzas de marea lo desintegrarán, creando un sistema de anillos comparable al de Saturno.'
  },
  {
    id: 'pluton', name: 'Plutón',
    categoria: 'Planeta Enano', clasificacion: 'Planeta Enano (Plutino)',
    color: '#C4A882', archivo: `${BASE}/Pluton.glb`, cameraOrbit: '0deg 80deg 180%',
    funcion: 'Planeta enano del Cinturón de Kuiper; símbolo del debate sobre la definición de planeta',
    ubicacion: 'Cinturón de Kuiper — 39,5 UA del Sol (media)',
    relacion: 'Caronte (luna binaria), Cinturón de Kuiper, Neptuno (resonancia orbital 2:3)',
    tamano: 'Diámetro 2.377 km — 18% del diámetro terrestre',
    importancia: 'Redefinió la categoría "planeta" en 2006; abrió la era de exploración del Cinturón de Kuiper',
    descripcion: 'Plutón fue el noveno planeta desde 1930 hasta 2006, cuando la IAU lo reclasificó como planeta enano. Ubicado en el Cinturón de Kuiper, tiene montañas de hielo de agua de hasta 3.500 m.',
    datoCurioso: 'Caronte es tan grande en relación a Plutón que ambos forman un sistema binario.',
    datos: { 'Diámetro': '2.377 km', 'Masa': '1,30 × 10²² kg', 'Temperatura': '−229 °C (promedio)', 'Atmósfera': 'N₂, CH₄, CO (tenue)', 'Rotación': '6,4 días', 'Órbita': '248 años', 'Lunas': '5 (Caronte, Nix, Hidra…)', 'Dist. al Sol': '39,5 UA (media)' },
    curiosidades: ['Reclasificado de planeta a planeta enano en agosto de 2006', '"Tombaugh Regio" tiene forma de corazón de 1.600 km de ancho', 'Su atmósfera se expande cuando se acerca al Sol en su órbita elíptica', 'Caronte es tan grande que juntos forman un sistema binario'],
    nota: 'La sonda New Horizons sobrevoló Plutón el 14 de julio de 2015 a solo 12.500 km, revelando una geología activa con posibles volcanes de hielo (criovulcanismo).'
  }
];

export const CATEGORIAS = [
  'Estrella', 'Planeta Rocoso', 'Satélite Natural',
  'Gigante Gaseoso', 'Gigante de Hielo', 'Planeta Enano'
];
